"""add revenue_yoy profit_yoy columns

Revision ID: ac0531848f21
Revises: e3919eb34883
Create Date: 2026-04-19 18:40:25.674366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0531848f21'
down_revision: Union[str, None] = 'e3919eb34883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_fundamentals', sa.Column('revenue_yoy', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('profit_yoy', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_fundamentals', 'profit_yoy')
    op.drop_column('stock_fundamentals', 'revenue_yoy')
    # ### end Alembic commands ###
