"""init

Revision ID: ccfa2c149fe1
Revises: 
Create Date: 2026-04-19 14:27:10.526364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccfa2c149fe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('related_industries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('market', sa.Enum('A', 'HK', name='market_enum'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('is_watchlist', sa.Boolean(), nullable=False),
    sa.Column('data_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.create_index(op.f('ix_stocks_is_watchlist'), 'stocks', ['is_watchlist'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.Enum('daily', 'event_driven', 'initial', name='report_type_enum'), nullable=False),
    sa.Column('conclusion', sa.String(length=200), nullable=True),
    sa.Column('overall_signal', sa.Enum('bullish', 'bearish', 'neutral', name='signal_enum'), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('fundamental_score', sa.Integer(), nullable=True),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_report_date'), 'analysis_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_analysis_reports_stock_id'), 'analysis_reports', ['stock_id'], unique=False)
    op.create_table('chip_distributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('price_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profit_ratio', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'calc_date', name='uq_chip_stock_date')
    )
    op.create_index(op.f('ix_chip_distributions_stock_id'), 'chip_distributions', ['stock_id'], unique=False)
    op.create_table('divergence_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('price_point1', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('price_point2', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('indicator_point1', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('indicator_point2', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divergence_signals_stock_id'), 'divergence_signals', ['stock_id'], unique=False)
    op.create_table('news_stock_relations',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['industry_news.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'stock_id')
    )
    op.create_table('profit_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('eps_forecast', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_profit_forecast', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_forecast', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('forward_pe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('analyst_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'forecast_year', 'source', name='uq_forecast_stock_year_source')
    )
    op.create_index(op.f('ix_profit_forecasts_stock_id'), 'profit_forecasts', ['stock_id'], unique=False)
    op.create_table('stock_daily_kline',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_kline_stock_date')
    )
    op.create_index('ix_kline_stock_date', 'stock_daily_kline', ['stock_id', 'trade_date'], unique=False)
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.Enum('quarterly', 'annual', 'ttm', name='period_type_enum'), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_ttm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cash_flow_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'period', 'period_type', name='uq_fundamental_stock_period')
    )
    op.create_index(op.f('ix_stock_fundamentals_stock_id'), 'stock_fundamentals', ['stock_id'], unique=False)
    op.create_table('stock_technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ma10', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('macd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rsi_6', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_24', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_j', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_indicator_stock_date')
    )
    op.create_index('ix_indicator_stock_date', 'stock_technical_indicators', ['stock_id', 'trade_date'], unique=False)
    op.create_table('supply_chains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('upstream', 'downstream', 'competitor', name='supply_chain_type_enum'), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_code', sa.String(length=10), nullable=True),
    sa.Column('product_desc', sa.Text(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('importance', sa.Enum('high', 'medium', 'low', name='importance_enum'), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_chains_stock_id'), 'supply_chains', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_chains_stock_id'), table_name='supply_chains')
    op.drop_table('supply_chains')
    op.drop_index('ix_indicator_stock_date', table_name='stock_technical_indicators')
    op.drop_table('stock_technical_indicators')
    op.drop_index(op.f('ix_stock_fundamentals_stock_id'), table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    op.drop_index('ix_kline_stock_date', table_name='stock_daily_kline')
    op.drop_table('stock_daily_kline')
    op.drop_index(op.f('ix_profit_forecasts_stock_id'), table_name='profit_forecasts')
    op.drop_table('profit_forecasts')
    op.drop_table('news_stock_relations')
    op.drop_index(op.f('ix_divergence_signals_stock_id'), table_name='divergence_signals')
    op.drop_table('divergence_signals')
    op.drop_index(op.f('ix_chip_distributions_stock_id'), table_name='chip_distributions')
    op.drop_table('chip_distributions')
    op.drop_index(op.f('ix_analysis_reports_stock_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_report_date'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_stocks_is_watchlist'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('industry_news')
    # ### end Alembic commands ###
