"""add revenue_yoy profit_yoy to stock_fundamentals

Revision ID: e3919eb34883
Revises: ccfa2c149fe1
Create Date: 2026-04-19 18:39:54.268702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3919eb34883'
down_revision: Union[str, None] = 'ccfa2c149fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
